USE tempdb
GO

CREATE DATABASE SYSTEM_PRESTAMOS_LF
GO

USE SYSTEM_PRESTAMOS_LF
GO

CREATE TABLE ESTADOS
(
COD_ESTADO INT PRIMARY KEY IDENTITY,
DESCRIPCION_ESTADO NVARCHAR(50)
)
GO

CREATE TABLE CLIENTES
(
COD_CLIENTE NVARCHAR(15) PRIMARY KEY,
IDENTIDAD_DEL_CLIENTE NVARCHAR(13) NOT NULL,
NOMBRE_CLIENTE NVARCHAR(50) NOT NULL,
APELLIDO_CLIENTE NVARCHAR(50) NOT NULL,
SEXO NVARCHAR(2) NOT NULL,
DIRECCION NVARCHAR(150) NOT NULL,
TELEFONO_CLIENTE NVARCHAR(15),
COD_ESTADO INT NOT NULL,
FECHA_MODIFICACION DATETIME 
)
GO

--TABLA DE PRESTAMOS
CREATE TABLE PRESTAMOS
(
COD_PRESTAMO NVARCHAR(15),
FECHA_INICIO DATE,
FECHA_FINAL DATE,
DESCRIPCION_PRESTAMO NVARCHAR(50),
PLAZO NVARCHAR(30),
MONTO MONEY,
CAPITAL_FINAL MONEY,
INTERES_FINAL MONEY,
TASA_INTERES nvarchar(10),
COD_CLIENTE nvarchar(15),
COD_ESTADO int
primary key(COD_PRESTAMO)
)
GO

-- TABLA DE DETALLE PRESTAMO
CREATE TABLE DETALLE_PRESTAMOS
(
COD_PRESTAMO NVARCHAR(15), 
COD_CUOTA INT,
CANTIDAD_CUOTA INT,
CANTIDA_INTERES MONEY,
CANTIDAD_CAPITAL MONEY,
FECHA_PAGO DATE 
PRIMARY KEY(COD_PRESTAMO,COD_CUOTA)
)
GO

-- Tabla para los Cargos de la Empresa
CREATE TABLE CARGOS
(
COD_PUESTO INT PRIMARY KEY IDENTITY,
DESCRIPCION_PUESTO NVARCHAR(50)
)
GO

-- Tabla para el control de empleados
CREATE TABLE EMPLEADOS
(
COD_EMPLEADO NVARCHAR(15) PRIMARY KEY,
NOMBRE_EMPLEADO NVARCHAR(50) NOT NULL,
APELLIDO_EMPLEADO NVARCHAR(50) NOT NULL,
TELEFONO_EMPLEADO NVARCHAR(20) NOT NULL,
NOMBRE_USUARIO NVARCHAR(50),
CONTRASEÑA NVARCHAR(50),
CORREO NVARCHAR(80),
SUELDO MONEY,
COD_PUESTO INT, 
COD_ESTADO INT
)
GO

CREATE TABLE PAGOS_PRESTAMOS
(
COD_PAGO NVARCHAR(15) PRIMARY KEY, 
SALDO_ANTERIOR MONEY,
SALDO_ACTUAL MONEY,
CUOTAS_PAGADAS INT,
COD_PRESTAMO NVARCHAR(15),
COD_ESTADO INT
)
GO

CREATE TABLE DETALLE_PAGOS_PRESTAMOS
(
COD_PAGO NVARCHAR(15),
COD_DETALLE_PAGO INT IDENTITY, 
NUMERO_CUOTA INT,
TOTAL_PAGO MONEY,
SALDO_PENDIENTE MONEY,
FECHA_TRANSACCION_PAGO DATETIME
PRIMARY KEY(COD_PAGO,COD_DETALLE_PAGO)
)
GO

CREATE TABLE HISTORIAL_PAGOS_PRESTAMOS
(
COD_PRESTAMO NVARCHAR(15) PRIMARY KEY,
DESCRIPCION_PRESTAMO NVARCHAR(50),
CUOTAS_PAGADAS INT,
INTERES MONEY,
CAPITAL MONEY,
CUOTA MONEY,
FECHA_PAGO_ULTIMA_CUOTA DATETIME ,
FECHA_INICIO DATE,
MONTO MONEY,
CAPITAL_FINAL MONEY,
INTERES_FINAL MONEY
)
GO

ALTER TABLE PRESTAMOS
	Add Constraint FK_CLIENTE$TieneUn$Prestamo
	Foreign Key(COD_CLIENTE) References CLIENTES(COD_CLIENTE)
	On UPDATE No Action
	On DELETE No Action
GO

ALTER TABLE PRESTAMOS
	Add Constraint FK_PRESTAMO$TieneUn$ESTADO
	Foreign Key(COD_ESTADO) References ESTADOS(COD_ESTADO)
	On UPDATE No Action
	On DELETE No Action
GO

ALTER TABLE CLIENTES
	Add Constraint FK_CLIENTE$TieneUn$Estado
	Foreign Key(COD_ESTADO) References ESTADOS(COD_ESTADO)
	On UPDATE No Action
	On DELETE No Action
GO

ALTER TABLE EMPLEADOS
	Add Constraint FK_EMPELADOS$TieneUn$PUESTO
	Foreign Key(COD_PUESTO) References CARGOS(COD_PUESTO)
	On UPDATE No Action
	On DELETE No Action
GO

ALTER TABLE EMPLEADOS
	Add Constraint FK_EMPELADOS$TieneUn$ESTADO
	Foreign Key(COD_ESTADO) References ESTADOS(COD_ESTADO)
	On UPDATE No Action
	On DELETE No Action
GO

ALTER TABLE DETALLE_PRESTAMOS
	Add Constraint FK_PRESTAMO$TieneUn$DATALLE$DE$CUOTAS
	Foreign Key(COD_PRESTAMO) References PRESTAMOS(COD_PRESTAMO)
	On UPDATE No Action
	On DELETE No Action
GO

ALTER TABLE PAGOS_PRESTAMOS
	Add Constraint FK_PRESTAMOS$TieneUn$PAGO
	Foreign Key(COD_PRESTAMO) References PRESTAMOS(COD_PRESTAMO)
	On UPDATE No Action
	On DELETE No Action
GO

ALTER TABLE PAGOS_PRESTAMOS
	Add Constraint FK_EMPELADOS$Tiene$Un$ESTADO
	Foreign Key(COD_ESTADO) References ESTADOS(COD_ESTADO)
	On UPDATE No Action
	On DELETE No Action
GO

ALTER TABLE DETALLE_PAGOS_PRESTAMOS
	Add Constraint FK_PAGO$TieneUn$DETALLE$DE$PAGO
	Foreign Key(COD_PAGO) References PAGOS_PRESTAMOS(COD_PAGO)
	On UPDATE No Action
	On DELETE No Action
GO

ALTER TABLE HISTORIAL_PAGOS_PRESTAMOS
	Add Constraint FK_PRESTAMOS$TieneUn$HISTORIA$DE$PAGO
	Foreign Key(COD_PRESTAMO) References PRESTAMOS(COD_PRESTAMO)
	On UPDATE No Action
	On DELETE No Action
GO

